/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../../src/app/MaterialModule/material.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/router/src/router_module';
import * as import4 from '@angular/common/src/localization';
import * as import5 from '@angular/platform-browser/src/browser/title';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from './material.component.ngfactory';
import * as import8 from '@angular/core/src/i18n/tokens';
import * as import9 from '../../../../src/app/MaterialModule/material.component';
import * as import10 from '@angular/router/src/router_config_loader';
class MaterialComponentModuleInjector extends import0.NgModuleInjector<import1.MaterialComponentModule> {
  _CommonModule_0:import2.CommonModule;
  _RouterModule_1:import3.RouterModule;
  _MaterialComponentModule_2:import1.MaterialComponentModule;
  __NgLocalization_3:import4.NgLocaleLocalization;
  __ROUTES_4:any[];
  __Title_5:import5.Title;
  constructor(parent:import6.Injector) {
    super(parent,[import7.MaterialComponentNgFactory],([] as any[]));
  }
  get _NgLocalization_3():import4.NgLocaleLocalization {
    if ((this.__NgLocalization_3 == null)) { (this.__NgLocalization_3 = new import4.NgLocaleLocalization(this.parent.get(import8.LOCALE_ID))); }
    return this.__NgLocalization_3;
  }
  get _ROUTES_4():any[] {
        if ((this.__ROUTES_4 == null)) { (this.__ROUTES_4 = [[{
          path: 'material',
          component: import9.MaterialComponent,
          data: {title: 'ChildComponent'}
        }
    ]]); }
    return this.__ROUTES_4;
  }
  get _Title_5():import5.Title {
    if ((this.__Title_5 == null)) { (this.__Title_5 = new import5.Title()); }
    return this.__Title_5;
  }
  createInternal():import1.MaterialComponentModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._RouterModule_1 = new import3.RouterModule(this.parent.get(import3.ROUTER_FORROOT_GUARD,(null as any)));
    this._MaterialComponentModule_2 = new import1.MaterialComponentModule();
    return this._MaterialComponentModule_2;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.RouterModule)) { return this._RouterModule_1; }
    if ((token === import1.MaterialComponentModule)) { return this._MaterialComponentModule_2; }
    if ((token === import4.NgLocalization)) { return this._NgLocalization_3; }
    if ((token === import10.ROUTES)) { return this._ROUTES_4; }
    if ((token === import5.Title)) { return this._Title_5; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const MaterialComponentModuleNgFactory:import0.NgModuleFactory<import1.MaterialComponentModule> = new import0.NgModuleFactory(MaterialComponentModuleInjector,import1.MaterialComponentModule);