/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../src/app/app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/material/core/compatibility/default-mode';
import * as import4 from '@angular/material/core/ripple/ripple';
import * as import5 from '@angular/material/button/button';
import * as import6 from '@angular/material/card/card';
import * as import7 from '@angular/material/chips/chip-list';
import * as import8 from '@angular/material/checkbox/checkbox';
import * as import9 from '@angular/material/core/line/line';
import * as import10 from '@angular/material/grid-list/grid-list';
import * as import11 from '@angular/forms/src/directives';
import * as import12 from '@angular/forms/src/form_providers';
import * as import13 from '@angular/material/core/platform/index';
import * as import14 from '@angular/material/input/input';
import * as import15 from '@angular/material/list/list';
import * as import16 from '@angular/material/progress-bar/progress-bar';
import * as import17 from '@angular/material/progress-spinner/progress-spinner';
import * as import18 from '@angular/material/core/portal/portal-directives';
import * as import19 from '@angular/material/core/overlay/overlay-directives';
import * as import20 from '@angular/material/select/index';
import * as import21 from '@angular/material/core/a11y/index';
import * as import22 from '@angular/material/sidenav/sidenav';
import * as import23 from '@angular/material/core/observe-content/observe-content';
import * as import24 from '@angular/material/tabs/tab-group';
import * as import25 from '@angular/material/toolbar/toolbar';
import * as import26 from '@angular/material/core/projection/projection';
import * as import27 from '@angular/material/core/rtl/dir';
import * as import28 from '@angular/material/button-toggle/button-toggle';
import * as import29 from '@angular/material/dialog/index';
import * as import30 from '@angular/http/src/http_module';
import * as import31 from '@angular/material/icon/icon';
import * as import32 from '@angular/material/menu/menu';
import * as import33 from '@angular/material/radio/radio';
import * as import34 from '@angular/material/slider/slider';
import * as import35 from '@angular/material/slide-toggle/slide-toggle';
import * as import36 from '@angular/material/snack-bar/snack-bar';
import * as import37 from '@angular/material/tooltip/tooltip';
import * as import38 from '@angular/material/module';
import * as import39 from '@angular/core/src/application_module';
import * as import40 from '@angular/platform-browser/src/browser';
import * as import41 from '@angular/router/src/router_module';
import * as import42 from '../../../src/app/childModule/child.module';
import * as import43 from '../../../src/app/childModule2/child.module';
import * as import44 from '../../../src/app/MaterialModule/material.module';
import * as import45 from '@angular/common/src/localization';
import * as import46 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import47 from '@angular/http/src/backends/browser_xhr';
import * as import48 from '@angular/http/src/base_response_options';
import * as import49 from '@angular/http/src/backends/xhr_backend';
import * as import50 from '@angular/http/src/base_request_options';
import * as import51 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import52 from '@angular/material/core/overlay/position/viewport-ruler';
import * as import53 from '@angular/material/core/platform/platform';
import * as import54 from '@angular/material/core/overlay/position/overlay-position-builder';
import * as import55 from '@angular/material/core/overlay/overlay-container';
import * as import56 from '@angular/core/src/application_init';
import * as import57 from '@angular/core/src/testability/testability';
import * as import58 from '@angular/core/src/application_ref';
import * as import59 from '@angular/material/core/overlay/overlay';
import * as import60 from '@angular/material/core/overlay/scroll/scroll-dispatcher';
import * as import61 from '@angular/material/core/a11y/interactivity-checker';
import * as import62 from '@angular/material/core/a11y/live-announcer';
import * as import63 from '@angular/material/core/coordination/unique-selection-dispatcher';
import * as import64 from '@angular/material/dialog/dialog';
import * as import65 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import66 from '@angular/material/icon/icon-registry';
import * as import67 from '@angular/core/src/linker/compiler';
import * as import68 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import69 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import70 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import71 from '@angular/core/src/animation/animation_queue';
import * as import72 from '@angular/core/src/linker/view_utils';
import * as import73 from '@angular/platform-browser/src/browser/title';
import * as import74 from '@angular/common/src/location/location';
import * as import75 from '@angular/router/src/url_tree';
import * as import76 from '@angular/router/src/router_outlet_map';
import * as import77 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import78 from '@angular/router/src/router_preloader';
import * as import79 from '@angular/core/src/di/injector';
import * as import80 from '../../node_modules/@angular/material/dialog/dialog-container.ngfactory';
import * as import81 from '../../node_modules/@angular/material/snack-bar/snack-bar-container.ngfactory';
import * as import82 from '../../node_modules/@angular/material/snack-bar/simple-snack-bar.ngfactory';
import * as import83 from '../../node_modules/@angular/material/tooltip/tooltip.ngfactory';
import * as import84 from './childModule/child.component.ngfactory';
import * as import85 from './childModule2/child.component.ngfactory';
import * as import86 from './MaterialModule/material.component.ngfactory';
import * as import87 from './error/pagenotfound.component.ngfactory';
import * as import88 from './app.component.ngfactory';
import * as import89 from '@angular/core/src/i18n/tokens';
import * as import90 from '@angular/core/src/zone/ng_zone';
import * as import91 from '@angular/core/src/application_tokens';
import * as import92 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import93 from '@angular/platform-browser/src/dom/events/key_events';
import * as import94 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import95 from '../../../src/app/childModule/child.component';
import * as import96 from '../../../src/app/childModule2/child.component';
import * as import97 from '../../../src/app/MaterialModule/material.component';
import * as import98 from '../../../src/app/error/pagenotfound.component';
import * as import99 from '@angular/common/src/location/platform_location';
import * as import100 from '@angular/common/src/location/location_strategy';
import * as import101 from '@angular/router/src/url_handling_strategy';
import * as import102 from '@angular/router/src/route_reuse_strategy';
import * as import103 from '@angular/router/src/router';
import * as import104 from '@angular/core/src/console';
import * as import105 from '@angular/http/src/interfaces';
import * as import106 from '@angular/http/src/http';
import * as import107 from '@angular/core/src/error_handler';
import * as import108 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import109 from '@angular/platform-browser/src/dom/animation_driver';
import * as import110 from '@angular/core/src/render/api';
import * as import111 from '@angular/core/src/security';
import * as import112 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import113 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import114 from '@angular/router/src/router_config_loader';
import * as import115 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import116 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _DefaultStyleCompatibilityModeModule_1:import3.DefaultStyleCompatibilityModeModule;
  _MdRippleModule_2:import4.MdRippleModule;
  _MdButtonModule_3:import5.MdButtonModule;
  _MdCardModule_4:import6.MdCardModule;
  _MdChipsModule_5:import7.MdChipsModule;
  _MdCheckboxModule_6:import8.MdCheckboxModule;
  _MdLineModule_7:import9.MdLineModule;
  _MdGridListModule_8:import10.MdGridListModule;
  _InternalFormsSharedModule_9:import11.InternalFormsSharedModule;
  _FormsModule_10:import12.FormsModule;
  _PlatformModule_11:import13.PlatformModule;
  _MdInputModule_12:import14.MdInputModule;
  _MdListModule_13:import15.MdListModule;
  _MdProgressBarModule_14:import16.MdProgressBarModule;
  _MdProgressSpinnerModule_15:import17.MdProgressSpinnerModule;
  _PortalModule_16:import18.PortalModule;
  _OverlayModule_17:import19.OverlayModule;
  _MdSelectModule_18:import20.MdSelectModule;
  _A11yModule_19:import21.A11yModule;
  _MdSidenavModule_20:import22.MdSidenavModule;
  _ObserveContentModule_21:import23.ObserveContentModule;
  _MdTabsModule_22:import24.MdTabsModule;
  _MdToolbarModule_23:import25.MdToolbarModule;
  _ProjectionModule_24:import26.ProjectionModule;
  _RtlModule_25:import27.RtlModule;
  _MdButtonToggleModule_26:import28.MdButtonToggleModule;
  _MdDialogModule_27:import29.MdDialogModule;
  _HttpModule_28:import30.HttpModule;
  _MdIconModule_29:import31.MdIconModule;
  _MdMenuModule_30:import32.MdMenuModule;
  _MdRadioModule_31:import33.MdRadioModule;
  _MdSliderModule_32:import34.MdSliderModule;
  _MdSlideToggleModule_33:import35.MdSlideToggleModule;
  _MdSnackBarModule_34:import36.MdSnackBarModule;
  _MdTooltipModule_35:import37.MdTooltipModule;
  _MaterialRootModule_36:import38.MaterialRootModule;
  _ApplicationModule_37:import39.ApplicationModule;
  _BrowserModule_38:import40.BrowserModule;
  _ROUTER_FORROOT_GUARD_39:any;
  _RouterModule_40:import41.RouterModule;
  _ChildModule_41:import42.ChildModule;
  _ChildModule2_42:import43.ChildModule2;
  _MaterialComponentModule_43:import44.MaterialComponentModule;
  _AppModule_44:import1.AppModule;
  __LOCALE_ID_45:any;
  __NgLocalization_46:import45.NgLocaleLocalization;
  __MATERIAL_COMPATIBILITY_MODE_47:any;
  __RadioControlRegistry_48:import46.RadioControlRegistry;
  __BrowserXhr_49:import47.BrowserXhr;
  __ResponseOptions_50:import48.BaseResponseOptions;
  __XSRFStrategy_51:any;
  __XHRBackend_52:import49.XHRBackend;
  __RequestOptions_53:import50.BaseRequestOptions;
  __Http_54:any;
  __HAMMER_GESTURE_CONFIG_55:import51.HammerGestureConfig;
  __ViewportRuler_56:import52.ViewportRuler;
  __Platform_57:import53.Platform;
  __OverlayPositionBuilder_58:import54.OverlayPositionBuilder;
  __OverlayContainer_59:import55.OverlayContainer;
  __ErrorHandler_60:any;
  __ApplicationInitStatus_61:import56.ApplicationInitStatus;
  __Testability_62:import57.Testability;
  _ApplicationRef__63:import58.ApplicationRef_;
  __ApplicationRef_64:any;
  __Overlay_65:import59.Overlay;
  __ScrollDispatcher_66:import60.ScrollDispatcher;
  __InteractivityChecker_67:import61.InteractivityChecker;
  __DomProjection_68:import26.DomProjection;
  __LiveAnnouncer_69:import62.LiveAnnouncer;
  __UniqueSelectionDispatcher_70:import63.UniqueSelectionDispatcher;
  __MdDialog_71:import64.MdDialog;
  __DomSanitizer_72:import65.DomSanitizerImpl;
  __MdIconRegistry_73:import66.MdIconRegistry;
  __MdSnackBar_74:import36.MdSnackBar;
  __Compiler_75:import67.Compiler;
  __APP_ID_76:any;
  __DOCUMENT_77:any;
  __EVENT_MANAGER_PLUGINS_78:any[];
  __EventManager_79:import68.EventManager;
  __DomSharedStylesHost_80:import69.DomSharedStylesHost;
  __AnimationDriver_81:any;
  __DomRootRenderer_82:import70.DomRootRenderer_;
  __NgProbeToken_83:any[];
  __RootRenderer_84:any;
  __Sanitizer_85:any;
  __AnimationQueue_86:import71.AnimationQueue;
  __ViewUtils_87:import72.ViewUtils;
  __IterableDiffers_88:any;
  __KeyValueDiffers_89:any;
  __SharedStylesHost_90:any;
  __Title_91:import73.Title;
  __ROUTES_92:any[];
  __ROUTER_CONFIGURATION_93:any;
  __LocationStrategy_94:any;
  __Location_95:import74.Location;
  __UrlSerializer_96:import75.DefaultUrlSerializer;
  __RouterOutletMap_97:import76.RouterOutletMap;
  __NgModuleFactoryLoader_98:import77.SystemJsNgModuleLoader;
  __Router_99:any;
  __ActivatedRoute_100:any;
  _NoPreloading_101:import78.NoPreloading;
  _PreloadingStrategy_102:any;
  _RouterPreloader_103:import78.RouterPreloader;
  __PreloadAllModules_104:import78.PreloadAllModules;
  __ROUTER_INITIALIZER_105:any;
  __APP_BOOTSTRAP_LISTENER_106:any[];
  constructor(parent:import79.Injector) {
    super(parent,[
      import80.MdDialogContainerNgFactory,
      import81.MdSnackBarContainerNgFactory,
      import82.SimpleSnackBarNgFactory,
      import83.TooltipComponentNgFactory,
      import84.ChildComponentNgFactory,
      import85.ChildComponent2NgFactory,
      import86.MaterialComponentNgFactory,
      import87.PageNotFoundComponentNgFactory,
      import88.AppComponentNgFactory
    ]
    ,[import88.AppComponentNgFactory]);
  }
  get _LOCALE_ID_45():any {
    if ((this.__LOCALE_ID_45 == null)) { (this.__LOCALE_ID_45 = import39._localeFactory(this.parent.get(import89.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_45;
  }
  get _NgLocalization_46():import45.NgLocaleLocalization {
    if ((this.__NgLocalization_46 == null)) { (this.__NgLocalization_46 = new import45.NgLocaleLocalization(this._LOCALE_ID_45)); }
    return this.__NgLocalization_46;
  }
  get _MATERIAL_COMPATIBILITY_MODE_47():any {
    if ((this.__MATERIAL_COMPATIBILITY_MODE_47 == null)) { (this.__MATERIAL_COMPATIBILITY_MODE_47 = false); }
    return this.__MATERIAL_COMPATIBILITY_MODE_47;
  }
  get _RadioControlRegistry_48():import46.RadioControlRegistry {
    if ((this.__RadioControlRegistry_48 == null)) { (this.__RadioControlRegistry_48 = new import46.RadioControlRegistry()); }
    return this.__RadioControlRegistry_48;
  }
  get _BrowserXhr_49():import47.BrowserXhr {
    if ((this.__BrowserXhr_49 == null)) { (this.__BrowserXhr_49 = new import47.BrowserXhr()); }
    return this.__BrowserXhr_49;
  }
  get _ResponseOptions_50():import48.BaseResponseOptions {
    if ((this.__ResponseOptions_50 == null)) { (this.__ResponseOptions_50 = new import48.BaseResponseOptions()); }
    return this.__ResponseOptions_50;
  }
  get _XSRFStrategy_51():any {
    if ((this.__XSRFStrategy_51 == null)) { (this.__XSRFStrategy_51 = import30._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_51;
  }
  get _XHRBackend_52():import49.XHRBackend {
    if ((this.__XHRBackend_52 == null)) { (this.__XHRBackend_52 = new import49.XHRBackend(this._BrowserXhr_49,this._ResponseOptions_50,this._XSRFStrategy_51)); }
    return this.__XHRBackend_52;
  }
  get _RequestOptions_53():import50.BaseRequestOptions {
    if ((this.__RequestOptions_53 == null)) { (this.__RequestOptions_53 = new import50.BaseRequestOptions()); }
    return this.__RequestOptions_53;
  }
  get _Http_54():any {
    if ((this.__Http_54 == null)) { (this.__Http_54 = import30.httpFactory(this._XHRBackend_52,this._RequestOptions_53)); }
    return this.__Http_54;
  }
  get _HAMMER_GESTURE_CONFIG_55():import51.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_55 == null)) { (this.__HAMMER_GESTURE_CONFIG_55 = new import51.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_55;
  }
  get _ViewportRuler_56():import52.ViewportRuler {
    if ((this.__ViewportRuler_56 == null)) { (this.__ViewportRuler_56 = new import52.ViewportRuler()); }
    return this.__ViewportRuler_56;
  }
  get _Platform_57():import53.Platform {
    if ((this.__Platform_57 == null)) { (this.__Platform_57 = new import53.Platform()); }
    return this.__Platform_57;
  }
  get _OverlayPositionBuilder_58():import54.OverlayPositionBuilder {
    if ((this.__OverlayPositionBuilder_58 == null)) { (this.__OverlayPositionBuilder_58 = new import54.OverlayPositionBuilder(this._ViewportRuler_56)); }
    return this.__OverlayPositionBuilder_58;
  }
  get _OverlayContainer_59():import55.OverlayContainer {
    if ((this.__OverlayContainer_59 == null)) { (this.__OverlayContainer_59 = new import55.OverlayContainer()); }
    return this.__OverlayContainer_59;
  }
  get _ErrorHandler_60():any {
    if ((this.__ErrorHandler_60 == null)) { (this.__ErrorHandler_60 = import40.errorHandler()); }
    return this.__ErrorHandler_60;
  }
  get _ApplicationInitStatus_61():import56.ApplicationInitStatus {
    if ((this.__ApplicationInitStatus_61 == null)) { (this.__ApplicationInitStatus_61 = new import56.ApplicationInitStatus(this.parent.get(import56.APP_INITIALIZER,(null as any)))); }
    return this.__ApplicationInitStatus_61;
  }
  get _Testability_62():import57.Testability {
    if ((this.__Testability_62 == null)) { (this.__Testability_62 = new import57.Testability(this.parent.get(import90.NgZone))); }
    return this.__Testability_62;
  }
  get _ApplicationRef_64():any {
    if ((this.__ApplicationRef_64 == null)) { (this.__ApplicationRef_64 = this._ApplicationRef__63); }
    return this.__ApplicationRef_64;
  }
  get _Overlay_65():import59.Overlay {
    if ((this.__Overlay_65 == null)) { (this.__Overlay_65 = new import59.Overlay(this._OverlayContainer_59,this,this._OverlayPositionBuilder_58,this._ApplicationRef_64,this,this.parent.get(import90.NgZone))); }
    return this.__Overlay_65;
  }
  get _ScrollDispatcher_66():import60.ScrollDispatcher {
    if ((this.__ScrollDispatcher_66 == null)) { (this.__ScrollDispatcher_66 = new import60.ScrollDispatcher()); }
    return this.__ScrollDispatcher_66;
  }
  get _InteractivityChecker_67():import61.InteractivityChecker {
    if ((this.__InteractivityChecker_67 == null)) { (this.__InteractivityChecker_67 = new import61.InteractivityChecker(this._Platform_57)); }
    return this.__InteractivityChecker_67;
  }
  get _DomProjection_68():import26.DomProjection {
    if ((this.__DomProjection_68 == null)) { (this.__DomProjection_68 = new import26.DomProjection()); }
    return this.__DomProjection_68;
  }
  get _LiveAnnouncer_69():import62.LiveAnnouncer {
    if ((this.__LiveAnnouncer_69 == null)) { (this.__LiveAnnouncer_69 = new import62.LiveAnnouncer(this.parent.get(import62.LIVE_ANNOUNCER_ELEMENT_TOKEN,(null as any)))); }
    return this.__LiveAnnouncer_69;
  }
  get _UniqueSelectionDispatcher_70():import63.UniqueSelectionDispatcher {
    if ((this.__UniqueSelectionDispatcher_70 == null)) { (this.__UniqueSelectionDispatcher_70 = new import63.UniqueSelectionDispatcher()); }
    return this.__UniqueSelectionDispatcher_70;
  }
  get _MdDialog_71():import64.MdDialog {
    if ((this.__MdDialog_71 == null)) { (this.__MdDialog_71 = new import64.MdDialog(this._Overlay_65,this)); }
    return this.__MdDialog_71;
  }
  get _DomSanitizer_72():import65.DomSanitizerImpl {
    if ((this.__DomSanitizer_72 == null)) { (this.__DomSanitizer_72 = new import65.DomSanitizerImpl()); }
    return this.__DomSanitizer_72;
  }
  get _MdIconRegistry_73():import66.MdIconRegistry {
    if ((this.__MdIconRegistry_73 == null)) { (this.__MdIconRegistry_73 = new import66.MdIconRegistry(this._Http_54,this._DomSanitizer_72)); }
    return this.__MdIconRegistry_73;
  }
  get _MdSnackBar_74():import36.MdSnackBar {
    if ((this.__MdSnackBar_74 == null)) { (this.__MdSnackBar_74 = new import36.MdSnackBar(this._Overlay_65,this._LiveAnnouncer_69)); }
    return this.__MdSnackBar_74;
  }
  get _Compiler_75():import67.Compiler {
    if ((this.__Compiler_75 == null)) { (this.__Compiler_75 = new import67.Compiler()); }
    return this.__Compiler_75;
  }
  get _APP_ID_76():any {
    if ((this.__APP_ID_76 == null)) { (this.__APP_ID_76 = import91._appIdRandomProviderFactory()); }
    return this.__APP_ID_76;
  }
  get _DOCUMENT_77():any {
    if ((this.__DOCUMENT_77 == null)) { (this.__DOCUMENT_77 = import40._document()); }
    return this.__DOCUMENT_77;
  }
  get _EVENT_MANAGER_PLUGINS_78():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_78 == null)) { (this.__EVENT_MANAGER_PLUGINS_78 = [
      new import92.DomEventsPlugin(),
      new import93.KeyEventsPlugin(),
      new import51.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_55)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_78;
  }
  get _EventManager_79():import68.EventManager {
    if ((this.__EventManager_79 == null)) { (this.__EventManager_79 = new import68.EventManager(this._EVENT_MANAGER_PLUGINS_78,this.parent.get(import90.NgZone))); }
    return this.__EventManager_79;
  }
  get _DomSharedStylesHost_80():import69.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_80 == null)) { (this.__DomSharedStylesHost_80 = new import69.DomSharedStylesHost(this._DOCUMENT_77)); }
    return this.__DomSharedStylesHost_80;
  }
  get _AnimationDriver_81():any {
    if ((this.__AnimationDriver_81 == null)) { (this.__AnimationDriver_81 = import40._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_81;
  }
  get _DomRootRenderer_82():import70.DomRootRenderer_ {
    if ((this.__DomRootRenderer_82 == null)) { (this.__DomRootRenderer_82 = new import70.DomRootRenderer_(this._DOCUMENT_77,this._EventManager_79,this._DomSharedStylesHost_80,this._AnimationDriver_81,this._APP_ID_76)); }
    return this.__DomRootRenderer_82;
  }
  get _NgProbeToken_83():any[] {
    if ((this.__NgProbeToken_83 == null)) { (this.__NgProbeToken_83 = [import41.routerNgProbeToken()]); }
    return this.__NgProbeToken_83;
  }
  get _RootRenderer_84():any {
    if ((this.__RootRenderer_84 == null)) { (this.__RootRenderer_84 = import94._createConditionalRootRenderer(this._DomRootRenderer_82,this.parent.get(import94.NgProbeToken,(null as any)),this._NgProbeToken_83)); }
    return this.__RootRenderer_84;
  }
  get _Sanitizer_85():any {
    if ((this.__Sanitizer_85 == null)) { (this.__Sanitizer_85 = this._DomSanitizer_72); }
    return this.__Sanitizer_85;
  }
  get _AnimationQueue_86():import71.AnimationQueue {
    if ((this.__AnimationQueue_86 == null)) { (this.__AnimationQueue_86 = new import71.AnimationQueue(this.parent.get(import90.NgZone))); }
    return this.__AnimationQueue_86;
  }
  get _ViewUtils_87():import72.ViewUtils {
    if ((this.__ViewUtils_87 == null)) { (this.__ViewUtils_87 = new import72.ViewUtils(this._RootRenderer_84,this._Sanitizer_85,this._AnimationQueue_86)); }
    return this.__ViewUtils_87;
  }
  get _IterableDiffers_88():any {
    if ((this.__IterableDiffers_88 == null)) { (this.__IterableDiffers_88 = import39._iterableDiffersFactory()); }
    return this.__IterableDiffers_88;
  }
  get _KeyValueDiffers_89():any {
    if ((this.__KeyValueDiffers_89 == null)) { (this.__KeyValueDiffers_89 = import39._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_89;
  }
  get _SharedStylesHost_90():any {
    if ((this.__SharedStylesHost_90 == null)) { (this.__SharedStylesHost_90 = this._DomSharedStylesHost_80); }
    return this.__SharedStylesHost_90;
  }
  get _Title_91():import73.Title {
    if ((this.__Title_91 == null)) { (this.__Title_91 = new import73.Title()); }
    return this.__Title_91;
  }
  get _ROUTES_92():any[] {
    if ((this.__ROUTES_92 == null)) { (this.__ROUTES_92 = [
        [{
          path: 'child',
          component: import95.ChildComponent,
          data: {title: 'ChildComponent'}
        }
      ],
        [{
          path: 'child2',
          component: import96.ChildComponent2,
          data: {title: 'ChildComponent'}
        }
      ],
        [{
          path: 'material',
          component: import97.MaterialComponent,
          data: {title: 'ChildComponent'}
        }
      ],
      [
        {
          path: '',
          redirectTo: 'child',
          pathMatch: 'full'
        }
        ,
        {
          path: 'child',
          component: import42.ChildModule,
          data: {title: 'Heroes List'}
        }
        ,
        {
          path: 'child2',
          component: import43.ChildModule2,
          data: {title: 'Heroes List'}
        }
        ,
        {
          path: 'material',
          component: import44.MaterialComponentModule,
          data: {title: 'Heroes List'}
        }
        ,
        {
          path: '**',
          component: import98.PageNotFoundComponent
        }

      ]

    ]
    ); }
    return this.__ROUTES_92;
  }
  get _ROUTER_CONFIGURATION_93():any {
    if ((this.__ROUTER_CONFIGURATION_93 == null)) { (this.__ROUTER_CONFIGURATION_93 = {}); }
    return this.__ROUTER_CONFIGURATION_93;
  }
  get _LocationStrategy_94():any {
    if ((this.__LocationStrategy_94 == null)) { (this.__LocationStrategy_94 = import41.provideLocationStrategy(this.parent.get(import99.PlatformLocation),this.parent.get(import100.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_93)); }
    return this.__LocationStrategy_94;
  }
  get _Location_95():import74.Location {
    if ((this.__Location_95 == null)) { (this.__Location_95 = new import74.Location(this._LocationStrategy_94)); }
    return this.__Location_95;
  }
  get _UrlSerializer_96():import75.DefaultUrlSerializer {
    if ((this.__UrlSerializer_96 == null)) { (this.__UrlSerializer_96 = new import75.DefaultUrlSerializer()); }
    return this.__UrlSerializer_96;
  }
  get _RouterOutletMap_97():import76.RouterOutletMap {
    if ((this.__RouterOutletMap_97 == null)) { (this.__RouterOutletMap_97 = new import76.RouterOutletMap()); }
    return this.__RouterOutletMap_97;
  }
  get _NgModuleFactoryLoader_98():import77.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_98 == null)) { (this.__NgModuleFactoryLoader_98 = new import77.SystemJsNgModuleLoader(this._Compiler_75,this.parent.get(import77.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_98;
  }
  get _Router_99():any {
    if ((this.__Router_99 == null)) { (this.__Router_99 = import41.setupRouter(this._ApplicationRef_64,this._UrlSerializer_96,this._RouterOutletMap_97,this._Location_95,this,this._NgModuleFactoryLoader_98,this._Compiler_75,this._ROUTES_92,this._ROUTER_CONFIGURATION_93,this.parent.get(import101.UrlHandlingStrategy,(null as any)),this.parent.get(import102.RouteReuseStrategy,(null as any)))); }
    return this.__Router_99;
  }
  get _ActivatedRoute_100():any {
    if ((this.__ActivatedRoute_100 == null)) { (this.__ActivatedRoute_100 = import41.rootRoute(this._Router_99)); }
    return this.__ActivatedRoute_100;
  }
  get _PreloadAllModules_104():import78.PreloadAllModules {
    if ((this.__PreloadAllModules_104 == null)) { (this.__PreloadAllModules_104 = new import78.PreloadAllModules()); }
    return this.__PreloadAllModules_104;
  }
  get _ROUTER_INITIALIZER_105():any {
    if ((this.__ROUTER_INITIALIZER_105 == null)) { (this.__ROUTER_INITIALIZER_105 = import41.initialRouterNavigation(this._Router_99,this._ApplicationRef_64,this._RouterPreloader_103,this._ROUTER_CONFIGURATION_93)); }
    return this.__ROUTER_INITIALIZER_105;
  }
  get _APP_BOOTSTRAP_LISTENER_106():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_106 == null)) { (this.__APP_BOOTSTRAP_LISTENER_106 = [this._ROUTER_INITIALIZER_105]); }
    return this.__APP_BOOTSTRAP_LISTENER_106;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._DefaultStyleCompatibilityModeModule_1 = new import3.DefaultStyleCompatibilityModeModule();
    this._MdRippleModule_2 = new import4.MdRippleModule();
    this._MdButtonModule_3 = new import5.MdButtonModule();
    this._MdCardModule_4 = new import6.MdCardModule();
    this._MdChipsModule_5 = new import7.MdChipsModule();
    this._MdCheckboxModule_6 = new import8.MdCheckboxModule();
    this._MdLineModule_7 = new import9.MdLineModule();
    this._MdGridListModule_8 = new import10.MdGridListModule();
    this._InternalFormsSharedModule_9 = new import11.InternalFormsSharedModule();
    this._FormsModule_10 = new import12.FormsModule();
    this._PlatformModule_11 = new import13.PlatformModule();
    this._MdInputModule_12 = new import14.MdInputModule();
    this._MdListModule_13 = new import15.MdListModule();
    this._MdProgressBarModule_14 = new import16.MdProgressBarModule();
    this._MdProgressSpinnerModule_15 = new import17.MdProgressSpinnerModule();
    this._PortalModule_16 = new import18.PortalModule();
    this._OverlayModule_17 = new import19.OverlayModule();
    this._MdSelectModule_18 = new import20.MdSelectModule();
    this._A11yModule_19 = new import21.A11yModule();
    this._MdSidenavModule_20 = new import22.MdSidenavModule();
    this._ObserveContentModule_21 = new import23.ObserveContentModule();
    this._MdTabsModule_22 = new import24.MdTabsModule();
    this._MdToolbarModule_23 = new import25.MdToolbarModule();
    this._ProjectionModule_24 = new import26.ProjectionModule();
    this._RtlModule_25 = new import27.RtlModule();
    this._MdButtonToggleModule_26 = new import28.MdButtonToggleModule();
    this._MdDialogModule_27 = new import29.MdDialogModule();
    this._HttpModule_28 = new import30.HttpModule();
    this._MdIconModule_29 = new import31.MdIconModule();
    this._MdMenuModule_30 = new import32.MdMenuModule();
    this._MdRadioModule_31 = new import33.MdRadioModule();
    this._MdSliderModule_32 = new import34.MdSliderModule();
    this._MdSlideToggleModule_33 = new import35.MdSlideToggleModule();
    this._MdSnackBarModule_34 = new import36.MdSnackBarModule();
    this._MdTooltipModule_35 = new import37.MdTooltipModule();
    this._MaterialRootModule_36 = new import38.MaterialRootModule();
    this._ApplicationModule_37 = new import39.ApplicationModule();
    this._BrowserModule_38 = new import40.BrowserModule(this.parent.get(import40.BrowserModule,(null as any)));
    this._ROUTER_FORROOT_GUARD_39 = import41.provideForRootGuard(this.parent.get(import103.Router,(null as any)));
    this._RouterModule_40 = new import41.RouterModule(this._ROUTER_FORROOT_GUARD_39);
    this._ChildModule_41 = new import42.ChildModule();
    this._ChildModule2_42 = new import43.ChildModule2();
    this._MaterialComponentModule_43 = new import44.MaterialComponentModule();
    this._AppModule_44 = new import1.AppModule();
    this._ApplicationRef__63 = new import58.ApplicationRef_(this.parent.get(import90.NgZone),this.parent.get(import104.Console),this,this._ErrorHandler_60,this,this._ApplicationInitStatus_61,this.parent.get(import57.TestabilityRegistry,(null as any)),this._Testability_62);
    this._NoPreloading_101 = new import78.NoPreloading();
    this._PreloadingStrategy_102 = this._NoPreloading_101;
    this._RouterPreloader_103 = new import78.RouterPreloader(this._Router_99,this._NgModuleFactoryLoader_98,this._Compiler_75,this,this._PreloadingStrategy_102);
    return this._AppModule_44;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.DefaultStyleCompatibilityModeModule)) { return this._DefaultStyleCompatibilityModeModule_1; }
    if ((token === import4.MdRippleModule)) { return this._MdRippleModule_2; }
    if ((token === import5.MdButtonModule)) { return this._MdButtonModule_3; }
    if ((token === import6.MdCardModule)) { return this._MdCardModule_4; }
    if ((token === import7.MdChipsModule)) { return this._MdChipsModule_5; }
    if ((token === import8.MdCheckboxModule)) { return this._MdCheckboxModule_6; }
    if ((token === import9.MdLineModule)) { return this._MdLineModule_7; }
    if ((token === import10.MdGridListModule)) { return this._MdGridListModule_8; }
    if ((token === import11.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_9; }
    if ((token === import12.FormsModule)) { return this._FormsModule_10; }
    if ((token === import13.PlatformModule)) { return this._PlatformModule_11; }
    if ((token === import14.MdInputModule)) { return this._MdInputModule_12; }
    if ((token === import15.MdListModule)) { return this._MdListModule_13; }
    if ((token === import16.MdProgressBarModule)) { return this._MdProgressBarModule_14; }
    if ((token === import17.MdProgressSpinnerModule)) { return this._MdProgressSpinnerModule_15; }
    if ((token === import18.PortalModule)) { return this._PortalModule_16; }
    if ((token === import19.OverlayModule)) { return this._OverlayModule_17; }
    if ((token === import20.MdSelectModule)) { return this._MdSelectModule_18; }
    if ((token === import21.A11yModule)) { return this._A11yModule_19; }
    if ((token === import22.MdSidenavModule)) { return this._MdSidenavModule_20; }
    if ((token === import23.ObserveContentModule)) { return this._ObserveContentModule_21; }
    if ((token === import24.MdTabsModule)) { return this._MdTabsModule_22; }
    if ((token === import25.MdToolbarModule)) { return this._MdToolbarModule_23; }
    if ((token === import26.ProjectionModule)) { return this._ProjectionModule_24; }
    if ((token === import27.RtlModule)) { return this._RtlModule_25; }
    if ((token === import28.MdButtonToggleModule)) { return this._MdButtonToggleModule_26; }
    if ((token === import29.MdDialogModule)) { return this._MdDialogModule_27; }
    if ((token === import30.HttpModule)) { return this._HttpModule_28; }
    if ((token === import31.MdIconModule)) { return this._MdIconModule_29; }
    if ((token === import32.MdMenuModule)) { return this._MdMenuModule_30; }
    if ((token === import33.MdRadioModule)) { return this._MdRadioModule_31; }
    if ((token === import34.MdSliderModule)) { return this._MdSliderModule_32; }
    if ((token === import35.MdSlideToggleModule)) { return this._MdSlideToggleModule_33; }
    if ((token === import36.MdSnackBarModule)) { return this._MdSnackBarModule_34; }
    if ((token === import37.MdTooltipModule)) { return this._MdTooltipModule_35; }
    if ((token === import38.MaterialRootModule)) { return this._MaterialRootModule_36; }
    if ((token === import39.ApplicationModule)) { return this._ApplicationModule_37; }
    if ((token === import40.BrowserModule)) { return this._BrowserModule_38; }
    if ((token === import41.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_39; }
    if ((token === import41.RouterModule)) { return this._RouterModule_40; }
    if ((token === import42.ChildModule)) { return this._ChildModule_41; }
    if ((token === import43.ChildModule2)) { return this._ChildModule2_42; }
    if ((token === import44.MaterialComponentModule)) { return this._MaterialComponentModule_43; }
    if ((token === import1.AppModule)) { return this._AppModule_44; }
    if ((token === import89.LOCALE_ID)) { return this._LOCALE_ID_45; }
    if ((token === import45.NgLocalization)) { return this._NgLocalization_46; }
    if ((token === import3.MATERIAL_COMPATIBILITY_MODE)) { return this._MATERIAL_COMPATIBILITY_MODE_47; }
    if ((token === import46.RadioControlRegistry)) { return this._RadioControlRegistry_48; }
    if ((token === import47.BrowserXhr)) { return this._BrowserXhr_49; }
    if ((token === import48.ResponseOptions)) { return this._ResponseOptions_50; }
    if ((token === import105.XSRFStrategy)) { return this._XSRFStrategy_51; }
    if ((token === import49.XHRBackend)) { return this._XHRBackend_52; }
    if ((token === import50.RequestOptions)) { return this._RequestOptions_53; }
    if ((token === import106.Http)) { return this._Http_54; }
    if ((token === import51.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_55; }
    if ((token === import52.ViewportRuler)) { return this._ViewportRuler_56; }
    if ((token === import53.Platform)) { return this._Platform_57; }
    if ((token === import54.OverlayPositionBuilder)) { return this._OverlayPositionBuilder_58; }
    if ((token === import55.OverlayContainer)) { return this._OverlayContainer_59; }
    if ((token === import107.ErrorHandler)) { return this._ErrorHandler_60; }
    if ((token === import56.ApplicationInitStatus)) { return this._ApplicationInitStatus_61; }
    if ((token === import57.Testability)) { return this._Testability_62; }
    if ((token === import58.ApplicationRef_)) { return this._ApplicationRef__63; }
    if ((token === import58.ApplicationRef)) { return this._ApplicationRef_64; }
    if ((token === import59.Overlay)) { return this._Overlay_65; }
    if ((token === import60.ScrollDispatcher)) { return this._ScrollDispatcher_66; }
    if ((token === import61.InteractivityChecker)) { return this._InteractivityChecker_67; }
    if ((token === import26.DomProjection)) { return this._DomProjection_68; }
    if ((token === import62.LiveAnnouncer)) { return this._LiveAnnouncer_69; }
    if ((token === import63.UniqueSelectionDispatcher)) { return this._UniqueSelectionDispatcher_70; }
    if ((token === import64.MdDialog)) { return this._MdDialog_71; }
    if ((token === import65.DomSanitizer)) { return this._DomSanitizer_72; }
    if ((token === import66.MdIconRegistry)) { return this._MdIconRegistry_73; }
    if ((token === import36.MdSnackBar)) { return this._MdSnackBar_74; }
    if ((token === import67.Compiler)) { return this._Compiler_75; }
    if ((token === import91.APP_ID)) { return this._APP_ID_76; }
    if ((token === import108.DOCUMENT)) { return this._DOCUMENT_77; }
    if ((token === import68.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_78; }
    if ((token === import68.EventManager)) { return this._EventManager_79; }
    if ((token === import69.DomSharedStylesHost)) { return this._DomSharedStylesHost_80; }
    if ((token === import109.AnimationDriver)) { return this._AnimationDriver_81; }
    if ((token === import70.DomRootRenderer)) { return this._DomRootRenderer_82; }
    if ((token === import58.NgProbeToken)) { return this._NgProbeToken_83; }
    if ((token === import110.RootRenderer)) { return this._RootRenderer_84; }
    if ((token === import111.Sanitizer)) { return this._Sanitizer_85; }
    if ((token === import71.AnimationQueue)) { return this._AnimationQueue_86; }
    if ((token === import72.ViewUtils)) { return this._ViewUtils_87; }
    if ((token === import112.IterableDiffers)) { return this._IterableDiffers_88; }
    if ((token === import113.KeyValueDiffers)) { return this._KeyValueDiffers_89; }
    if ((token === import69.SharedStylesHost)) { return this._SharedStylesHost_90; }
    if ((token === import73.Title)) { return this._Title_91; }
    if ((token === import114.ROUTES)) { return this._ROUTES_92; }
    if ((token === import41.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_93; }
    if ((token === import100.LocationStrategy)) { return this._LocationStrategy_94; }
    if ((token === import74.Location)) { return this._Location_95; }
    if ((token === import75.UrlSerializer)) { return this._UrlSerializer_96; }
    if ((token === import76.RouterOutletMap)) { return this._RouterOutletMap_97; }
    if ((token === import115.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_98; }
    if ((token === import103.Router)) { return this._Router_99; }
    if ((token === import116.ActivatedRoute)) { return this._ActivatedRoute_100; }
    if ((token === import78.NoPreloading)) { return this._NoPreloading_101; }
    if ((token === import78.PreloadingStrategy)) { return this._PreloadingStrategy_102; }
    if ((token === import78.RouterPreloader)) { return this._RouterPreloader_103; }
    if ((token === import78.PreloadAllModules)) { return this._PreloadAllModules_104; }
    if ((token === import41.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_105; }
    if ((token === import91.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_106; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__63.ngOnDestroy();
    this._RouterPreloader_103.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);